/**
 * Google Fonts Downloader
 * Downloads Google Fonts and generates self-hosted font CSS
 *
 * This script ensures privacy compliance (GDPR) and offline support
 * by hosting fonts locally instead of using Google's CDN.
 *
 * Usage: node scripts/download-fonts.js
 */

const https = require('https');
const fs = require('fs');
const path = require('path');

// Fonts to download with their configurations
const FONTS_CONFIG = [
  {
    family: 'Inter',
    weights: [300, 400, 500, 600, 700],
    styles: ['normal'],
    subsets: ['latin', 'latin-ext'],
    display: 'swap'
  },
  {
    family: 'JetBrains Mono',
    weights: [400, 500, 700],
    styles: ['normal'],
    subsets: ['latin'],
    display: 'swap'
  }
];

class GoogleFontsDownloader {
  constructor() {
    this.outputDir = path.join(__dirname, '../src/assets/fonts');
    this.cssOutputPath = path.join(__dirname, '../src/assets/styles/fonts.css');
    this.cssContent = [];
  }

  /**
   * Main entry point
   */
  async downloadAllFonts() {
    console.log('🔽 Starting Google Fonts download...\n');

    // Ensure output directories exist
    this.ensureDirectories();

    // Add CSS header
    this.cssContent.push('/* Auto-generated font faces */');
    this.cssContent.push('/* DO NOT EDIT MANUALLY - Generated by scripts/download-fonts.js */');
    this.cssContent.push('/* Last generated: ' + new Date().toISOString() + ' */');
    this.cssContent.push('');

    // Download each font family
    for (const fontConfig of FONTS_CONFIG) {
      await this.downloadFont(fontConfig);
    }

    // Write CSS file
    fs.writeFileSync(this.cssOutputPath, this.cssContent.join('\n'));
    console.log(`\n✅ Font CSS written to ${this.cssOutputPath}`);
    console.log('\n🎉 All fonts downloaded successfully!');
    console.log('\n📝 Next steps:');
    console.log('   1. Import fonts.css in your global styles');
    console.log('   2. Use font-family: "Inter" or "JetBrains Mono" in your CSS');
  }

  /**
   * Ensure output directories exist
   */
  ensureDirectories() {
    if (!fs.existsSync(this.outputDir)) {
      fs.mkdirSync(this.outputDir, { recursive: true });
    }

    const stylesDir = path.dirname(this.cssOutputPath);
    if (!fs.existsSync(stylesDir)) {
      fs.mkdirSync(stylesDir, { recursive: true });
    }
  }

  /**
   * Download a single font family with all weights and styles
   */
  async downloadFont(config) {
    console.log(`📦 Processing ${config.family}...`);

    const familyDir = path.join(this.outputDir, this.slugify(config.family));
    if (!fs.existsSync(familyDir)) {
      fs.mkdirSync(familyDir, { recursive: true });
    }

    for (const weight of config.weights) {
      for (const style of config.styles) {
        await this.downloadFontVariant(config, weight, style, familyDir);
      }
    }

    console.log(`✅ ${config.family} completed\n`);
  }

  /**
   * Download a specific font variant (weight + style combination)
   */
  async downloadFontVariant(config, weight, style, familyDir) {
    try {
      // Get Google Fonts CSS
      const googleCss = await this.fetchGoogleFontsCss(config.family, weight, style);

      // Extract woff2 URL from CSS
      const fontUrl = this.extractFontUrl(googleCss);
      if (!fontUrl) {
        console.warn(`  ⚠️  Could not find font URL for ${config.family} ${weight} ${style}`);
        return;
      }

      // Generate filename
      const filename = `${this.slugify(config.family)}-${weight}-${style}.woff2`;
      const filepath = path.join(familyDir, filename);

      // Download font file
      await this.downloadFile(fontUrl, filepath);
      console.log(`  ✓ Downloaded ${filename}`);

      // Generate @font-face CSS
      this.generateFontFace(config, weight, style, filename);

    } catch (error) {
      console.error(`  ❌ Error downloading ${config.family} ${weight} ${style}:`, error.message);
    }
  }

  /**
   * Fetch Google Fonts CSS metadata
   */
  async fetchGoogleFontsCss(family, weight, style) {
    const familyEncoded = family.replace(/\s+/g, '+');
    const styleParam = style === 'italic' ? 'ital,' : '';
    const url = `https://fonts.googleapis.com/css2?family=${familyEncoded}:${styleParam}wght@${weight}&display=swap`;

    return new Promise((resolve, reject) => {
      const options = {
        headers: {
          // Use modern browser user agent to get woff2 format
          'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
        }
      };

      https.get(url, options, (res) => {
        let data = '';
        res.on('data', (chunk) => data += chunk);
        res.on('end', () => resolve(data));
      }).on('error', reject);
    });
  }

  /**
   * Extract .woff2 URL from Google Fonts CSS
   */
  extractFontUrl(css) {
    // Match: url(https://fonts.gstatic.com/...woff2)
    const match = css.match(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2)\)/);
    return match ? match[1] : null;
  }

  /**
   * Download a file from URL to local path
   */
  async downloadFile(url, filepath) {
    return new Promise((resolve, reject) => {
      const file = fs.createWriteStream(filepath);

      https.get(url, (response) => {
        response.pipe(file);

        file.on('finish', () => {
          file.close();
          resolve();
        });

        file.on('error', (err) => {
          fs.unlink(filepath, () => reject(err));
        });
      }).on('error', (err) => {
        fs.unlink(filepath, () => reject(err));
      });
    });
  }

  /**
   * Generate @font-face CSS declaration
   */
  generateFontFace(config, weight, style, filename) {
    const fontPath = `/assets/fonts/${this.slugify(config.family)}/${filename}`;

    const fontFace = `
@font-face {
  font-family: '${config.family}';
  font-style: ${style};
  font-weight: ${weight};
  font-display: ${config.display};
  src: url('${fontPath}') format('woff2');
  /* Self-hosted for privacy and performance */
}`;

    this.cssContent.push(fontFace);
  }

  /**
   * Convert text to URL-friendly slug
   */
  slugify(text) {
    return text.toLowerCase().replace(/\s+/g, '-');
  }
}

// Execute the script
if (require.main === module) {
  const downloader = new GoogleFontsDownloader();
  downloader.downloadAllFonts()
    .catch((error) => {
      console.error('\n❌ Fatal error:', error);
      process.exit(1);
    });
}

module.exports = GoogleFontsDownloader;
